### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by f5xs-0000a**
https://www.dictionary.com/e/their-vs-there-vs-theyre/

### CODE REVIEW

**Comment by jhpratt** [comment]
Heh, I'm a native English speaker and am well aware of this. I was probably changing what I typed and missed it. It should actually just be "the", given the surrounding context.

**Comment by f5xs-0000a** [comment]
You're right. I missed part of the context. My bad. Nonetheless, the error sticks out for now and requires fixing.

**Comment by jhpratt** [comment]
Yeah, what I meant is if you change it to "the" I'll merge it 😁

**Comment by f5xs-0000a** [comment]
Here it is. Have fun.

**Comment by jhpratt** [comment]
Thanks!

**Pull request merged**
