### PR TITLE
Add no_std support and CI check for embedded

### PR DESCRIPTION
**Pull request by PTaylor-us**
I am pretty new to Rust and am using it for embedded. I was unable to compile this library for an embedded target even when supplying the `--no-default-features` build option as seen below:

(using rustc 1.44.0-nightly (94d346360 2020-04-09))
```
> cargo +nightly build --target thumbv7em-none-eabihf --no-default-features
   Compiling standback v0.2.2 (C:\Users\Peter\.cargo\registry\src\github.com1ecc6299db9ec823\standback-0.2.2)
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed
error: aborting due to previous error
For more information about this error, try `rustc --explain E0463`.
error: could not compile `standback`.
To learn more, run the command again with --verbose.
```

I added a conditional `#![no_std]` in the crate root (not(std)) and also as well as in `1_42.rs` where needed. In addition, I added an embedded target for the check performed with the `--no-default-features` flag. It is my understanding that this is one option to ensure that the check actually fails if not `no_std`. It does appear that rustc versions before 1.42 will still fail. I'm not sure what would be required to get those working.

### CODE REVIEW

**Comment by jhpratt** [comment]
Looks like it's failing for a simple reason — `#[cfg_attr(not(std), no_std)]` should be replaced with `#[cfg(std)]`. `#![no_std]` (note the `!`) is something used at the crate level to make it work without the standard library. What we need to do here is conditionally enable the API — in this case if the standard library is enabled.

As for CI, I'm actually going to opt just have a single check for an embedded environment, rather than check _everything_ on that alone. This is especially important given it's a tier 2 target.

Would you prefer to make these changes yourself, or would you like me to do them? It's mostly trivial replacement, but it's still a learning experience :slightly_smiling_face: CI can be tricky, though.

**Comment by PTaylor-us** [comment]
Looks like I got a little copy/paste happy. I would love to make the changes. Thanks.

**Comment by PTaylor-us** [comment]
I'm going to keep working on this.

**Comment by PTaylor-us** [comment]
Ok, I think that is it. You said you wanted just a single test with the embedded target, but I just added a duplicate `cargo check --no-default-features` with the `--target` argument using the matrix. It was definitely helpful to have it test all the versions with the embedded target, but may be a bit redundant to run it on all the OSs.

**Comment by PTaylor-us** [comment]
These changes are required to resolve time-rs/time#246

**Comment by jhpratt** [comment]
Thanks! I'll take a look at the CI bit later today; that's not a big deal.

**Comment by jhpratt** [comment]
Superfluous CI failure, given that commit was only bumping version. Merging.

**Pull request merged**
